INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0866', 'MAJ.', 'KASUMBA EDWARD', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0866', 'MAJ.', 'KASUMBA EDWARD', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/106', 'MAJ.', 'SEBBI ISMAIL', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1194', 'MAJ.', 'MATEGE JOHNSON', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/121', 'MAJ.', 'KYAMUFUMBA KIZITO HENRY', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1674', 'MAJ.', 'DRAVU EZRA', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1674', 'MAJ.', 'DRAVU EZRA', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/195', 'MAJ.', 'KIGOZI NATHAN', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2052', 'MAJ.', 'BAITWA NATHAN', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2175', 'MAJ.', 'KASALI ENOCK', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/222', 'MAJ.', 'SHAMASHAMA JOHN', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/253', 'MAJ.', 'KABEGAMBIRE JIMMY', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/257', 'MAJ.', 'BIGANJA JOSHUA KAKOOKO', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3038', 'MAJ.', 'BAGUMA ISSA MERCY', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/308', 'MAJ.', 'KAGINA BERNARD', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3301', 'MAJ.', 'KILAMA MIKE', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/4424', 'MAJ.', 'KATO BRIGHT', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/469', 'MAJ.', 'SETIMBA GODFEY', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/469', 'MAJ.', 'SETIMBA GODFEY', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/59', 'MAJ.', 'KALANZI JAMES', 'UNCLAIMED', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/6622', 'MAJ.', 'TWESIGYE ABDALLAH', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/6646', 'MAJ.', 'BALINDA .K. JOSEPH', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/851', 'MAJ.', 'KAKEBE LIVINGSTONE', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/917', 'MAJ.', 'KIYINGI PATRICK', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO1425', 'MAJ.', 'AYUBU AJOBE', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO1893', 'MAJ.', 'SEGAWA GODFREY', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO2745', 'MAJ.', 'KUSAMBIZI DAN', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO4366', 'MAJ.', 'MAKOSA SHERIF', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO4458', 'MAJ.', 'SSESANGA ISSA', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO4458', 'MAJ.', 'SSESANGA ISSA', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO477', 'MAJ.', 'MUWONGE SAM', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO568', 'MAJ.', 'NKONGE CHRISTOPHER', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO6765', 'MAJ.', 'KAZAHURA CLOVIS', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO741', 'MAJ.', 'MPABWA FRANCIS', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO8377', 'MAJ.', 'JOHNSON FRIDAY KARIMU', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0137', 'MAJ.', 'BYECAKA BATUMBYA', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0487', 'MAJ.', 'KAWESA LAWRENCE', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1315', 'MAJ.', 'BYAKWAGA ERIC', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/223', 'MAJ.', 'MARURU BOAZ', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/64', 'MAJ.', 'MAGANJA ENOCK', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/656', 'MAJ.', 'KEKIKOMO JACKSON', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2175', 'MAJ.', 'KASALI ENOCK', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2217', 'MAJ.', 'RWASHANDE KHAM', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO6152', 'MAJ.', 'MUKASA-KIKOMEKO WILLY', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO1572', 'MAJ.', 'EZAMA PETER', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/091', 'MAJ.', 'BWENDE JERO .B.', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1400', 'MAJ.', 'MDYANABO FRED', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1558', 'MAJ.', 'LUBWAMA STEVEN', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1558', 'MAJ.', 'LUBWAMA STEVEN', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO568', 'MAJ.', 'NKONGE CHRISTOPHER', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 992', 'MAJ.', 'LUBEGA MOSES', 'NOT ON DATA', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1184', 'MAJ.', 'KYAKABALE BEREBERA FRED', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/257', 'MAJ.', 'BIGANJA JOSHUA KAKOOKO', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO65', 'MAJ.', 'MWENEMUZEE NATHAN', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1117', 'MAJ.', 'KIFUBA FRANK', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 6487', 'MAJ.', 'BWAMBALE STEPHEN', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 760', 'MAJ.', 'GONZAGA MORRUT ALOYSIOUS', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/01365', 'MAJ.', 'TURYAHIKAYO JOHNSON', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0680', 'MAJ.', 'MUNYANEZA MUSUNGU', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1194', 'MAJ.', 'MATEGE JOHNSON', 'INCOMPLETE', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/121', 'MAJ.', 'KYAMUFUMBA KIZITO HENRY', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1383', 'MAJ.', 'GIDUDU MILTON', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/149', 'MAJ.', 'TWOYEM WILFRED', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1674', 'MAJ.', 'DRAVU EZRA', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/222', 'MAJ.', 'SHAMASHAMA JOHN', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/226', 'MAJ.', 'TUMUSIME ROBERT', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2790', 'MAJ.', 'NKAYARWA GEORGE', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/281', 'MAJ.', 'KIIZA DAVID', 'INCOMPLETE', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/314', 'MAJ.', 'KATENDE FRANCIS', 'PAID', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/64', 'MAJ.', 'MAGANJA ENOCK', 'PAID', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/6852', 'MAJ.', 'MUKOROGO HARUNA', 'PAID', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/7046', 'MAJ.', 'KAPUCHU MUSA .M.', 'PAID', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/718', 'MAJ.', 'WAIJAHI WILLY', 'PAID', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/851', 'MAJ.', 'KAKEBE LIVINGSTONE', 'PAID', 'KAMPALA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO1351', 'MAJ.', 'MUGISHA ELLY .B.', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO171', 'MAJ.', 'AHIMBISIBWE ENOCK', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO171', 'MAJ.', 'AHIMBISIBWE ENOCK', 'PAID', 'MUKONO');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO173', 'MAJ.', 'KANABI MOSES', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO453', 'MAJ.', 'LUBOWA ROBERT', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO474', 'MAJ.', 'KABENDE PATRICK', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO783', 'MAJ.', 'LUKABWA EDWARD', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/622', 'MAJ.', 'ONDOGA ABAS', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/622', 'MAJ.', 'ONDOGA ABAS', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/622', 'MAJ.', 'ONDOGA ABAS', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RA59033', 'MAJ.', 'TURYASINGURA CHARLES', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 1223', 'MAJ.', 'BYARUGABA JOSEPH', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 145', 'MAJ.', 'ZAKYE ROBERT', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 282', 'MAJ.', 'SSEMPA JOLLY', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3345', 'MAJ.', 'LODUK ANDREW', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3345', 'MAJ.', 'LODUK ANDREW', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3358', 'MAJ.', 'OKELLO LAGARA LUKA', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 571', 'MAJ.', 'SEMPA SALAAMA ABDU', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 571', 'MAJ.', 'SEMPA SALAAMA ABDU', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 802', 'MAJ.', 'SSEBAGALA JOSEPH', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 831', 'MAJ.', 'WALUSIMBI JOSEPH', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 89', 'MAJ.', 'BYENSI WILLIAM', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/00243', 'MAJ.', 'KIGGUNDU SMART SELESTINO', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/02302', 'MAJ.', 'KATABARWA JOHN', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/0542', 'MAJ.', 'NTEGE KIMSON', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/06934', 'MAJ.', 'OTUKEI JOHN ROBERT', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1400', 'MAJ.', 'MDYANABO FRED', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/149', 'MAJ.', 'TWOYEM WILFRED', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/149', 'MAJ.', 'TWOYEM WILFRED', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1638', 'MAJ.', 'OJAMBO STEPHEN', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2068', 'MAJ.', 'MANYINDO SIMON', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2175', 'MAJ.', 'KASALI ENOCK', 'INCOMPLETE', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/286', 'MAJ.', 'SEKITO DAVID IVAN', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/308', 'MAJ.', 'KAGINA BERNARD', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/314', 'MAJ.', 'KATENDE FRANCIS', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3340', 'MAJ.', 'MALI LEON OZI', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3351', 'MAJ.', 'OBWON JACK OCHEN', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3351', 'MAJ.', 'OBWON JACK OCHEN', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3600', 'MAJ.', 'CHUA EVAN', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/392', 'MAJ.', 'KISEKA WILLIAM', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/43', 'MAJ.', 'BAMWANGA NYANSIO', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/444', 'MAJ.', 'LUBEGA SIMON SALONGO', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/59', 'MAJ.', 'KALANZI JAMES', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/656', 'MAJ.', 'KEKIKOMO JACKSON', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6622', 'MAJ.', 'TWESIGYE ABDALLAH', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/7092', 'MAJ.', 'KAKURU GEORGE', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/851', 'MAJ.', 'KAKEBE LIVINGSTONE', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/8661', 'MAJ.', 'AKOL OMONGOT ROMANO', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/8661', 'MAJ.', 'AKOL OMONGOT ROMANO', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/913', 'MAJ.', 'WADRI GABRIEL', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/913', 'MAJ.', 'WADRI GABRIEL', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1425', 'MAJ.', 'AYUBU AJOBE', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO173', 'MAJ.', 'KANABI MOSES', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO260', 'MAJ.', 'GITTA PADDY .L.', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2745', 'MAJ.', 'KUSAMBIZI DAN', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2745', 'MAJ.', 'KUSAMBIZI DAN', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5301', 'MAJ.', 'OKOT RUBANGA-KENE', 'PAID', 'JINJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5301', 'MAJ.', 'OKOT RUBANGA-KENE', 'PAID', 'ARUA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO971', 'MAJ.', 'WAMALA GAVA', 'PAID', 'ARUA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/06379', 'MAJ.', 'SEMPA OLIVIA MAZZI', 'PAID', 'ARUA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 6390', 'CAPT.', 'SEBAKAKI K SULLY', 'PAID', 'ARUA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UR01311', 'CAPT.', 'KIBETI PATRICK WILSON', 'PAID', 'ARUA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UR91213', 'CAPT.', 'AZIZ BEY DENNIS', 'PAID', 'ARUA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'KAR1312', 'CAPT.', 'KINALWA SAM', 'PAID', 'KARAMOJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UML', 'CAPT.', 'BYALEERO FRANK', 'PAID', 'KARAMOJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'DA', 'CAPT.', 'LAPYEM MARK', 'PAID', 'KARAMOJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'RUHANGA ARUHO MOSES', 'PAID', 'KARAMOJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'ARAPU CHARLES', 'PAID', 'KARAMOJA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'AZIZ BEY DENNIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'NGYENDO FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'KARIBUTI DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'GAYIRA GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'KYAASIIMA GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'UD', 'CAPT.', 'KATO DAVIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'KAR', 'CAPT.', 'MASADDE YIGA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'KAR', 'CAPT.', 'KATUNGYE IGARA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'KAR', 'CAPT.', 'BYARUHANGA ELIAS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'KAR', 'CAPT.', 'MUGUMYA ALEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('EXG', 'KAR', 'CAPT.', 'NABASA ARTHUR', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1199', 'CAPT.', 'ATUKUNDA STEPHEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1422', 'CAPT.', 'AMANI ADAKI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1864', 'CAPT.', 'SEBADUKA FRANK', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/20', 'CAPT.', 'KASHANKU SHABAN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2813', 'CAPT.', 'MUJUNI ABUDALA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3312', 'CAPT.', 'ALIKU PANGARASIO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3666', 'CAPT.', 'MBAZIIRA JIMMY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/6409', 'CAPT.', 'WAAKO MULOKI DAUDI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO1500', 'CAPT.', 'LOROT STEPHEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO3363', 'CAPT.', 'LAPYEM MARK', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO346', 'CAPT.', 'SEBOWA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO346', 'CAPT.', 'SEBOWA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO4192', 'CAPT.', 'KAGANDA SPERATUS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO6572', 'CAPT.', 'NSOMBYA ALPHONSE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO723', 'CAPT.', 'BATANYISAKO MILTON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO897', 'CAPT.', 'ELINO EZABU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO934', 'CAPT.', 'NUWAGABA GODMAN', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 7655', 'CAPT.', 'NABIMBA SAMSON', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/4271', 'CAPT.', 'KIWANUKA FRED', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'R0/1833', 'CAPT.', 'KIGOZI STEPHEN', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'R0339', 'CAPT.', 'MUSISI FRED', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RA/50947', 'CAPT.', 'OPOKA PAUL', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RA/533', 'CAPT.', 'SEMPIJA HUSSEIN BIN', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RA/533', 'CAPT.', 'SEMPIJA HUSSEIN BIN', 'UNCLAIMED', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 0489', 'CAPT.', 'KIBIRA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 0489', 'CAPT.', 'KIBIRA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 0489', 'CAPT.', 'KIBIRA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 0489', 'CAPT.', 'KIBIRA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 112', 'CAPT.', 'BOSSA CHRISOPHER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1206', 'CAPT.', 'KWESIGA GEOFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1257', 'CAPT.', 'MBAZIIRA STEPHEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 132', 'CAPT.', 'NKOORA BUSINGE PETER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1539', 'CAPT.', 'OUSI MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1581', 'CAPT.', 'ABELE JUMA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1680', 'CAPT.', 'OKIM JOHN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1877', 'CAPT.', 'RUTAGWA GERGORI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2069', 'CAPT.', 'KIRYOWA NOAH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2069', 'CAPT.', 'KIRYOWA NOAH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 209', 'CAPT.', 'KYAWE HUGHES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2157', 'CAPT.', 'MULINDE GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2264', 'CAPT.', 'KAMYUFU JOHSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2477', 'CAPT.', 'SANTANA FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2485', 'CAPT.', 'KALANZI GEORGE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2797', 'CAPT.', 'ODOKI JUSTINE BRIGHT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2797', 'CAPT.', 'ODOKI JUSTINE BRIGHT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 289', 'CAPT.', 'TINKASIMIRE CHRIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 2949', 'CAPT.', 'IGA GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 307', 'CAPT.', 'MIGADDE SULA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 3185', 'CAPT.', 'OGWAL DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 3382', 'CAPT.', 'OKENE JOEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4090', 'CAPT.', 'ODENG VINCENT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4203', 'CAPT.', 'KAWERE JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4312', 'CAPT.', 'KIMERA STEPHEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 473', 'CAPT.', 'KIWANUKA BEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4901', 'CAPT.', 'NTAMBI ISAAC', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4925', 'CAPT.', 'BUSINDO KAGENI HENRY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5232', 'CAPT.', 'ONONO FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5320', 'CAPT.', 'AYUBU MUSA GULE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5320', 'CAPT.', 'AYUBU MUSA GULE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5620', 'CAPT.', 'BYARUHAMGA MILTON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5620', 'CAPT.', 'BYARUHAMGA MILTON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5911', 'CAPT.', 'OCHAYA JINO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5911', 'CAPT.', 'OCHAYA JINO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 6060', 'CAPT.', 'NKALUBO GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 6730', 'CAPT.', 'MUGUMYA ALEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 6747', 'CAPT.', 'EWANGU MILTON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 697', 'CAPT.', 'ISOKE RWORRA CYPRIAN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 7667', 'CAPT.', 'KIIZA SEIKO ALLI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 8060', 'CAPT.', 'OYET WALIKI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 900', 'CAPT.', 'DUMBA DAN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO.0332', 'CAPT.', 'KABUSENENE MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO.2169', 'CAPT.', 'KIVUMBI AMOS.T', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO.6402', 'CAPT.', 'IHWEZO MWESIGYE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/01139', 'CAPT.', 'OGWAL ALFRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0270', 'CAPT.', 'MANGEREZA GEORGE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0291', 'CAPT.', 'ZENKO KIGGUNDU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0537', 'CAPT.', 'KAMANYA RICHARD JOEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/07988', 'CAPT.', 'OTEMA OTHUBA SOLOMON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/07988', 'CAPT.', 'OTEMA OTHUBA SOLOMON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/07988', 'CAPT.', 'OTEMA OTHUBA SOLOMON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/0974', 'CAPT.', 'TUMWINE GEOFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1033', 'CAPT.', 'SENONO JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1033', 'CAPT.', 'SENONO JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/10644', 'CAPT.', 'BAREGYESA ABEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/10647', 'CAPT.', 'EMPIANGU ALEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1198', 'CAPT.', 'KYAMANYWA ROBERT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1268', 'CAPT.', 'TINKAMANYIRE BENON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1432', 'CAPT.', 'NYABWERE NATHAN BAKER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/146', 'CAPT.', 'MONDAY DOUGLAS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/147', 'CAPT.', 'KIBULA ISAAC', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1599', 'CAPT.', 'MAGARA KELILI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1599', 'CAPT.', 'MAGARA KELILI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1635', 'CAPT.', 'GAWAYA JOSEPH MUWOYA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1672', 'CAPT.', 'NYANKODI DAN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1686', 'CAPT.', 'MAGANDA HUSSEIN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1818', 'CAPT.', 'KABUYE SAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1818', 'CAPT.', 'KABUYE SAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1864', 'CAPT.', 'SEBADUKA FRANK', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1864', 'CAPT.', 'SEBADUKA FRANK', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1904', 'CAPT.', 'LUGEMWA RONALD', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2155', 'CAPT.', 'MAJANJA FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2191', 'CAPT.', 'OKUDOT JACKSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2191', 'CAPT.', 'OKUDOT JACKSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2290', 'CAPT.', 'BATHELOMEW KATEREGA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2314', 'CAPT.', 'KAKUTO JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2424', 'CAPT.', 'KAVUMA CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2470', 'CAPT.', 'KITAKA MATTE HENRY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2579', 'CAPT.', 'LAMEK BOSSA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2784', 'CAPT.', 'AKIIKI JAFFER B', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2890', 'CAPT.', 'BYARUHANGA TOM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/290', 'CAPT.', 'KIZZA WILLEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2948', 'CAPT.', 'KAKUMBA ALLI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2948', 'CAPT.', 'KAKUMBA ELLY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2964', 'CAPT.', 'TUMWINE ALEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2988', 'CAPT.', 'KAWEKE ANGEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2988', 'CAPT.', 'KAWEKE ANGEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3004', 'CAPT.', 'BAGUMA CHRIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3004', 'CAPT.', 'BAGUMA CHRIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3096', 'CAPT.', 'KIMULI SAMUEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3096', 'CAPT.', 'KIMULI SAMUEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3134', 'CAPT.', 'NAZARIO NWEKWASIZE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/322', 'CAPT.', 'MWESIGYE HAMU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3276', 'CAPT.', 'KALEMERA CHARLES .S.', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3290', 'CAPT.', 'OMONGO JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/340', 'CAPT.', 'KAWESA CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3456', 'CAPT.', 'KANYWANI DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3517', 'CAPT.', 'WASSWA CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3577', 'CAPT.', 'BULAMAGA FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3577', 'CAPT.', 'BULAMAGA FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3577', 'CAPT.', 'BULAMAGA FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3625', 'CAPT.', 'SSEMWANGA STEPHEN SALONGO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3666', 'CAPT.', 'MBAZIIRA JIMMY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3697', 'CAPT.', 'EBUGA HARUNA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3697', 'CAPT.', 'EBUGA HARUNA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3744', 'CAPT.', 'NSENGA GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/3828', 'CAPT.', 'APILLA MAX APEAL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/388', 'CAPT.', 'KIBUKA WILLIAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/394', 'CAPT.', 'SAKU DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/394', 'CAPT.', 'SAKU DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/416', 'CAPT.', 'KANYEREZI DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/459', 'CAPT.', 'WASWA SHEM SALONGO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/475', 'CAPT.', 'SITAKANGE THOMAS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/494', 'CAPT.', 'LUBWAMA DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5034', 'CAPT.', 'WOFUNILA SAULO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/505', 'CAPT.', 'OLIRI SALONGO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5162', 'CAPT.', 'KIWANUKA MUHAMMED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5323', 'CAPT.', 'MUHAMED BABALE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5370', 'CAPT.', 'JUMATUTU TABORA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/546', 'CAPT.', 'LUBOWA GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5468', 'CAPT.', 'OKELLO RICHARD', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5484', 'CAPT.', 'EBEMA JOHN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5487', 'CAPT.', 'ALUMA JOSEPH JERRY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5504', 'CAPT.', 'OCHEN ABONG DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5660', 'CAPT.', 'MUTESASIRA SUNDAY SEGIRINYA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5665', 'CAPT.', 'RUBAGUMYA LAWRENCE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/570', 'CAPT.', 'NDAMAGYE KAGARAMA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5876', 'CAPT.', 'MUYAKA CHRIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/604', 'CAPT.', 'KATEREGA SAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6071', 'CAPT.', 'MUHAIRWE JOHN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/634', 'CAPT.', 'KYEYUNE ABDU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/634', 'CAPT.', 'KYEYUNE ABDU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/634', 'CAPT.', 'KYEYUNE ABDU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6344', 'CAPT.', 'ECHUMAN LEVI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6398', 'CAPT.', 'OKELLO GEORGE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6409', 'CAPT.', 'WAAKO MULOKI DAUDI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6486', 'CAPT.', 'KYOMUHENDO CRISTOPHER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6486', 'CAPT.', 'KYOMUHENDO CRISTOPHER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6511', 'CAPT.', 'NYAGAHIMA JAMES BIVETE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6626', 'CAPT.', 'MAKOKO MURARA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6666', 'CAPT.', 'BAGUMA JONSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6805', 'CAPT.', 'KATO CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6946', 'CAPT.', 'MUGUME NABOTH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6970', 'CAPT.', 'OPIT BOND ROBERT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6985', 'CAPT.', 'AKOMI BENON VUNI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/7051', 'CAPT.', 'OGWANG MICHAEL ADDIOS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/7068', 'CAPT.', 'NSIMBI GODFREY Dr.', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/7668', 'CAPT.', 'ANGUMA COLLEB', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/830', 'CAPT.', 'SERUGO YOWAKIMU', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/832', 'CAPT.', 'KAGWA EDWARD', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/8387', 'CAPT.', 'KAMBAMU STEPHEN.H', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/840', 'CAPT.', 'KAYONDO DIIRO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/842', 'CAPT.', 'RWABAMBALI DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/8962', 'CAPT.', 'TAREMWA HENRY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/9311', 'CAPT.', 'BAZILIO OPIO L', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/954', 'CAPT.', 'TWESIGYE GEOFFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/975', 'CAPT.', 'KAGWA PADDY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1000', 'CAPT.', 'KIZITO JOHN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1009', 'CAPT.', 'ABIRIGA TITO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1022', 'CAPT.', 'KAKANDE SAMUEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1641', 'CAPT.', 'WANAHA PHILIP', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1683', 'CAPT.', 'MUKAMA SAMUEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2178', 'CAPT.', 'SETIMBA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2178', 'CAPT.', 'SETIMBA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2257', 'CAPT.', 'LUBOYERA ABDUL NASSER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2257', 'CAPT.', 'LUBOYERA ABDUL NASSER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2279', 'CAPT.', 'RWABALANDA PETER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2442', 'CAPT.', 'NKOGE FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2497', 'CAPT.', 'BYEKWASO GABRIEL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2697', 'CAPT.', 'ENGWEDU JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2708', 'CAPT.', 'EKAU JIMRO MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2887', 'CAPT.', 'VUKONI JIMRAY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2916', 'CAPT.', 'MUWANGA JOHN BOSCO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2930', 'CAPT.', 'MWESIGYE FRANCO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO3172', 'CAPT.', 'NKAMBWE STEPHEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO330', 'CAPT.', 'SENTONGO JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO3323', 'CAPT.', 'IDDI MUBARAK EMONG', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO3356', 'CAPT.', 'LWANGA HERBERT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO3474', 'CAPT.', 'TWEHEY JOHNSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO3474', 'CAPT.', 'TWEHEY JOHNSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO3711', 'CAPT.', 'KIKAWA HENRY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO4012', 'CAPT.', 'AGWARU PETER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO4076', 'CAPT.', 'MUSISI JACKSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO4127', 'CAPT.', 'KAMANYIRE SALAPIO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO4604', 'CAPT.', 'BYARUGABA CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO486', 'CAPT.', 'MUTUMBA ANTHONY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5062', 'CAPT.', 'MUWONGE JACKSON KAGWA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5177', 'CAPT.', 'AYOO PATRICK', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5283', 'CAPT.', 'KULE JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5463', 'CAPT.', 'KIMERA OYERA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5959', 'CAPT.', 'MUSEKUPA JUMA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6342', 'CAPT.', 'OLANGO MORIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6342', 'CAPT.', 'OLANGO MORIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6342', 'CAPT.', 'OLANGO MORIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6342', 'CAPT.', 'OLANGO MORIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6385', 'CAPT.', 'OCHAYA KOMAKECH CHRIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6512', 'CAPT.', 'OKALANY CHARLES AKOL', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6572', 'CAPT.', 'NSOMBYA ALPHONSE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6804', 'CAPT.', 'LWANGA ROGERS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO6840', 'CAPT.', 'MUSA CHRISTOPHER ATUA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO687', 'CAPT.', 'MUGISHA EDISON .S.', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO7255', 'CAPT.', 'KATUMBA JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO786', 'CAPT.', 'SERUYANGE NIXON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO9320', 'CAPT.', 'OKET YOT ROBERT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO934', 'CAPT.', 'NUWAGABA GODMAN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO965', 'CAPT.', 'MUSTAFA IGGA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO966', 'CAPT.', 'NABEMBEZI HILL MARK', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 1566', 'CAPT.', 'ODOKI COREY FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3412', 'CAPT.', 'ACHIGA MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3475', 'CAPT.', 'KABUGA JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3475', 'CAPT.', 'KABUGA JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 501', 'CAPT.', 'SEBUWUFU RICHARD', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 5838', 'CAPT.', 'MUSHABE GEORGE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 5919', 'CAPT.', 'BARAHUKWA LAWRENCE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 7134', 'CAPT.', 'WANYAMA FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO.890', 'CAPT.', 'KALIZIBWE TOM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/10215', 'CAPT.', 'TWAKIRWA DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1189', 'CAPT.', 'MUNANURA JOHN JONES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1372', 'CAPT.', 'KULUBA CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2218', 'CAPT.', 'KACUMITANA EDWARD', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/301', 'CAPT.', 'MAYANJA OJUKWA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/301', 'CAPT.', 'MAYANJA OJUKWA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/4767', 'CAPT.', 'KANA SAFI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/827', 'CAPT.', 'SEMANDA CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1442', 'CAPT.', 'NAKHAIMA FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1498', 'CAPT.', 'ODEKA WILSON', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO319', 'CAPT.', 'KASSIM YAHAYA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5283', 'CAPT.', 'KULE JOSEPH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 6730', 'CAPT.', 'MUGUMYA ALEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/2784', 'CAPT.', 'AKIIKI JAFFER B', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO1561', 'CAPT.', 'NAMANYA JOAB', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 5022', 'CAPT.', 'OKWIR ALEX', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/1354', 'CAPT.', 'IRUMBA WILLIAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 1773', 'CAPT.', 'BAGIRE GEORGE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 2157', 'CAPT.', 'MULINDE GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 3207', 'CAPT.', 'MAKANGA APOLLO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 501', 'CAPT.', 'SEBUWUFU RICHARD', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO 753', 'CAPT.', 'RWIKWERA PETER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/01139', 'CAPT.', 'OGWAL ALFRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/10828', 'CAPT.', 'BANGA BOAZ', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/5484', 'CAPT.', 'EBEMA JOHN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO/6805', 'CAPT.', 'KATO CHARLES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2285', 'CAPT.', 'MPIRIRWE COSMA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO2442', 'CAPT.', 'NKOGE FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('VETS', 'RO5046', 'CAPT.', 'ELIAS ELIAS PERE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 379', 'CAPT.', 'KASOLO SAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 6390', 'CAPT.', 'SEBAKAKI K SULLY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 7279', 'CAPT.', 'MUKURASI CHRISTOPHER', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3458', 'CAPT.', 'MWOROZI FRED.B.', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3492', 'CAPT.', 'MUSANA VINCENT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3844', 'CAPT.', 'KANKIRIHO FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO3356', 'CAPT.', 'LWANGA HERBERT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 380', 'CAPT.', 'KIGUNDU FRANCIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 442', 'CAPT.', 'SEKABOJJA JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1100', 'CAPT.', 'SENTEZA SAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1107', 'CAPT.', 'GUMISIZAMU SAM', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2007', 'CAPT.', 'NAMUJUNGA LUUTU MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2623', 'CAPT.', 'TUMWEBAZE GEOFFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/2962', 'CAPT.', 'BATARINGAYA DENIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/363', 'CAPT.', 'KAMOMO EDWIN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/6381', 'CAPT.', 'MUGISHA VALERIAN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/3290', 'CAPT.', 'OMONGO JAMES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RA 7009', 'CAPT.', 'MONDAY EDWARD BASEMERA', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RA/04359', 'CAPT.', 'SSENYIMBA GODFREY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 0462', 'CAPT.', 'KATO DAVIS', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1264', 'CAPT.', 'MAKANGA MONDAY', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1341', 'CAPT.', 'KIDIMU MISAKI', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1539', 'CAPT.', 'OUSI MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 1982', 'CAPT.', 'GOMA NATAL DAVID', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 3071', 'CAPT.', 'SSEBUFU NOAH', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 3600', 'CAPT.', 'KAASAMI STEVEN', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4270', 'CAPT.', 'KITYO ATANAZIO', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4653', 'CAPT.', 'KAMYA MOSES', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 4692', 'CAPT.', 'BAGUMA FRED', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 5838', 'CAPT.', 'MUSHABE GEORGE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 7651', 'CAPT.', 'OKONE NELSON KASULE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 7656', 'CAPT.', 'MATOVU JOHN BENEDICT', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO 7675', 'CAPT.', 'BUSULWA LIVINGSTONE', 'PAID', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO.4790', 'CAPT.', 'KASHILLING PETER', 'INCOMPLETE', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/07988', 'CAPT.', 'OTEMA OTHUBA SOLOMON', 'INCOMPLETE', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/129', 'CAPT.', 'RWAMUKAGA GORDON', 'INCOMPLETE', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1320', 'CAPT.', 'PIPINO FRANCIS', 'INCOMPLETE', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/135', 'CAPT.', 'MUCOKORI PETER', 'INCOMPLETE', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1422', 'CAPT.', 'AMANI ADAKI', 'INCOMPLETE', 'MBARARA');
INSERT INTO army_personnel (category, army_no, rank, name, status, district) VALUES ('SBS', 'RO/1686', 'CAPT.', 'MAGANDA HUSSEIN', 'INCOMPLETE', 'MBARARA');
